var words = {
    "positive": [
        "good",
        "great",
        "very good",
        "tremendous",
        "fantastic",
        "amazing",
        "terrific",
        "best",
        "winning",
        "huge",
        "classy",
        "nice",
        "beautiful",
        "smart",
        "very highly educated"
    ],
    "negative": [
        "sad",
        "outragious",
        "stupid",
        "not good",
        "bad",
        "very bad",
        "so not good",
        "dangerous",
        "lying",
        "failing",
        "stupid",
        "so called",
        "dishonest",
        "fake",
        "low energy",
        "tough",
        "weak",
        "zero",
        "lightweight",
        "moron",
        "wrong",
        "nasty",
        "disgrace"
    ],
    "neutral": [],
    "other": [
        "jobs",
        "job",
        "everyone",
        "handful",
        "utterly",
        "wall",
        "apocalyptic",
        "nuclear",
        "words",
        "hell",
        "spreading",
        "obviously",
        "businessman",
        "going",
        "know",
        "people",
        "want",
        "think",
        "brain",
        "right",
        "country",
        "lot",
        "money",
        "look",
        "mean",
        "way",
        "make",
        "really",
        "love",
        "time",
        "doing",
        "trump",
        "tell",
        "win",
        "thing",
        "things",
        "believe",
        "world",
        "everybody",
        "guy",
        "years",
        "okay",
        "big",
        "bigly",
        "million",
        "billion",
        "talk",
        "deal",
        "thank",
        "president",
        "wall",
        "number",
        "happen",
        "happened",
        "actually",
        "talking",
        "little",
        "saying",
        "states",
        "better",
        "incredible",
        "remember",
        "problem",
        "person",
        "sombody",
        "probably"
    ]
};

module.exports = words;
