var words = {
    "positive": [
        "good",
        "great",
        "great, great",
        "better",
        "greatest",
        "important",
        "very important",
        "very good",
        "tremendous",
        "fantastic",
        "amazing",
        "terrific",
        "best",
        "winning",
        "huge",
        "classy",
        "nice",
        "beautiful",
        "smart",
        "very highly educated",
        "underrated",
        "strong",
        "very strong",
        "strongman",
        "fighter",
        "big",
        "huuuge",
        "enormous",
    ],
    "negative": [
        "tiny",
        "worst",
        "boring",
        "sad",
        "outragious",
        "stupid",
        "not good",
        "bad",
        "very bad",
        "so not good",
        "dangerous",
        "lying",
        "failing",
        "stupid",
        "so called",
        "dishonest",
        "fake",
        "ridiculous",
        "low energy",
        "tough",
        "weak",
        "zero",
        "joke",
        "very weak",
        "scam",
        "hater",
        "loser",
        "total loser",
        "lightweight",
        "moron",
        "wrong",
        "nasty",
        "so nasty",
        "disgrace",
        "mean",
        "very mean",
        "crooked",
        "so crooked",
        "racist",
        "sexist",
        "ugly",
        "very ugly",
        "hidious",
        "unfair",
        "very unfair",
        "disastrous",
        "disaster",
        "tanked",
        "underachiving",
        "lie",
        "total lie",
        "problem",
        "terrible",
        "failure",
        "total failure",
        "crazy",
        "super crazy",
        "gross",
        "very gross",
        "scumbag",
        "total scumbag",
        "dumb",
        "very dumb",
        "so dumb",
        "total mess",
        "pathetic",
        "very pathetic",
        "snowflake",
        "overrated",
        "hypocrite",
        "sleazy",
        "baby",
        "little",
        "little baby",
    ],
    "neutral": [],
    "other": [
        "jobs",
        "job",
        "everyone",
        "handful",
        "utterly",
        "wall",
        "apocalyptic",
        "nuclear",
        "words",
        "hell",
        "spreading",
        "obviously",
        "businessman",
        "going",
        "know",
        "people",
        "want",
        "think",
        "brain",
        "right",
        "country",
        "lot",
        "money",
        "look",
        "mean",
        "way",
        "make",
        "really",
        "love",
        "time",
        "doing",
        "trump",
        "tell",
        "win",
        "court",
        "sue",
        "thing",
        "things",
        "believe",
        "world",
        "everybody",
        "guy",
        "years",
        "okay",
        "big",
        "bigly",
        "million",
        "billion",
        "talk",
        "deal",
        "thank",
        "president",
        "wall",
        "number",
        "happen",
        "happened",
        "actually",
        "talking",
        "little",
        "saying",
        "states",
        "better",
        "incredible",
        "remember",
        "problem",
        "person",
        "somebody",
        "probably",
        "opposition",
        "opposer",
        "rival",
        "total",
        "throw",
        "rating",
        "immigration",
        "muslims",
        "mexicans",
        "true",
        "false",
        "liberal",
        "absolutely",
        "again",
    ]
};

module.exports = words;
